### ISSUE TITLE
Typos en vrac

### ISSUE THREAD

**Issue by cferr** [mquinson/prog_scala#6]
TD3, section 1.1 : "simply sweeps over all solutions" -> "(simply / just) sweep over all the solutions" (just me semble plus adapté que simply, dans le sens où il y a une unique chose à faire mais pas forcément simple. Sweep : pas de "s" si c'est à l'impératif (contentez-vous de balayer les solutions). Et évidemment, un the car on sait quelles sont les solutions, ce ne sont pas des concepts mais des choses tangibles, toutes choses étant relatives bien entendu).
TD3, section 1.2 : "generating every knapsacks" -> "generating every knapsack" (derrière every, c'est un singulier)
TD3, section 3 : "a bread-first search" -> "a breadth-first search" (le pain, c'est bon, mais le parcours en largeur, c'est mieux). Dans la même phrase "the set can be empty if we reached a leaf" -> "the set can be empty if we have reached a leaf" (la feuille, nous l'avons toujours en main...)

TD2, un peu partout : je dirais "electric dipoles" plutôt que "electrical dipoles", idem pour "electric circuits" au lieu de "electrical circuits". Cela dit, je ne suis pas sûr de ça à 100% .
TD2, section 1.0 : "a serie circuit" -> "a series circuit" (c'est ainsi au singulier en anglais, et c'est la même pour les séries en maths)
Du coup, même erreur à la question 2, à la questiion 3.

**Comment by mquinson** [comment]
Ok, j'ai tout intégré, merci beaucoup.
